[server]
headless = true
runOnSave = false
address = "0.0.0.0"
port = 8080
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(levelname)s %(message)s"

[browser]
gatherUsageStats = false